'use client';

import { useState } from 'react';
import Link from 'next/link';

export default function AdminReports() {
  // 1. MOCK DATA: Updated to match the rich data generated by the AI Upload Results
  const [reports] = useState([
    {
      id: 'RPT-001',
      type: 'Longitudinal Crack',
      location: 'EDSA, Caloocan',
      date: 'Oct 12, 2023',
      severity: 'Moderate',
      status: 'Pending',
      confidence: '94.2%',
      description: 'The AI detected significant structural wear along the shoulder of the road.',
      fileName: 'Road_Scan_001.mp4',
      aiObservations: [
        'Crack depth exceeds 2cm',
        'Branching patterns identified',
        'Potential base-layer failure',
        'Immediate sealing recommended'
      ]
    },
    {
      id: 'RPT-002',
      type: 'Pothole',
      location: 'Monumento Circle',
      date: 'Oct 11, 2023',
      severity: 'Critical',
      status: 'In Review',
      confidence: '98.7%',
      description: 'Massive pothole in the middle lane causing vehicles to swerve. Estimated depth is over 5 inches.',
      fileName: 'IMG_8842.jpg',
      aiObservations: [
        'High risk of vehicular damage',
        'Debris scattered in 1m radius',
        'Water pooling inside crater',
        'Requires immediate patching'
      ]
    },
  ]);

  // 2. STATE: Tracks the ID of the currently expanded report
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const toggleReport = (id: string) => {
    setExpandedId((prev) => (prev === id ? null : id));
  };

  return (
    <div className="min-h-screen bg-[#525252]">
      
      {/* ==========================================
          CURVED BLACK HEADER SECTION
      ========================================== */}
      <div className="bg-black text-white rounded-b-[50px] px-10 pt-32 pb-12 shadow-2xl relative z-0">
        <div className="max-w-6xl mx-auto flex justify-between items-end">
          <div>
            <h1 className="text-4xl md:text-5xl font-black mb-2">Reports</h1>
            <p className="text-[#3b82f6] text-sm font-bold uppercase tracking-widest">Master Database</p>
          </div>
          <Link href="/admin" className="text-zinc-400 hover:text-white font-bold text-sm transition-colors">
            &larr; Back to Dashboard
          </Link>
        </div>
      </div>

      {/* ==========================================
          MAIN CONTENT: SEARCH & LIST
      ========================================== */}
      <div className="max-w-6xl mx-auto px-4 md:px-10 mt-8 relative z-10 pb-20">
        
        {/* Search Bar */}
        <div className="mb-10">
          <input 
            type="text" 
            placeholder="Search reports by location, severity, or ID..." 
            className="w-full bg-white rounded-full px-8 py-4 text-black font-bold shadow-lg focus:outline-none focus:ring-4 focus:ring-[#3b82f6]/50 transition-all placeholder-gray-400"
          />
        </div>

        {/* Dynamic List Panels */}
        <div className="flex flex-col gap-6">
          {reports.map((report) => {
            const isOpen = expandedId === report.id;

            return (
              <div 
                key={report.id}
                className="bg-white rounded-[30px] p-6 md:p-8 shadow-xl transition-transform duration-300 hover:-translate-y-1"
              >
                {/* TOP ROW: Always Visible */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
                  <div>
                    <div className="flex items-center gap-3 mb-1">
                      <h3 className="text-black font-black text-2xl">{report.id} - {report.type}</h3>
                      <span className={`px-3 py-1 text-[10px] font-black uppercase tracking-wider rounded-full ${
                        report.severity === 'Critical' ? 'bg-red-100 text-red-600' : 
                        report.severity === 'Severe' ? 'bg-orange-100 text-orange-600' :
                        report.severity === 'Moderate' ? 'bg-yellow-100 text-yellow-600' :
                        'bg-green-100 text-green-600'
                      }`}>
                        {report.severity}
                      </span>
                    </div>
                    <p className="text-gray-500 font-bold text-sm">Location: {report.location} | Date: {report.date}</p>
                  </div>
                  
                  <button 
                    onClick={() => toggleReport(report.id)}
                    className={`px-8 py-3 rounded-full font-bold text-sm transition-all active:scale-95 shadow-lg ${
                      isOpen 
                        ? 'bg-zinc-200 text-zinc-600 hover:bg-zinc-300 shadow-none' 
                        : 'bg-[#3b82f6] text-white hover:bg-blue-600'
                    }`}
                  >
                    {isOpen ? 'Close View' : 'Review Match'}
                  </button>
                </div>

                {/* BOTTOM ROW: The Animated "Mini View" Dropdown */}
                <div className={`grid transition-[grid-template-rows,opacity] duration-500 ease-in-out ${
                  isOpen ? 'grid-rows-[1fr] opacity-100 mt-6' : 'grid-rows-[0fr] opacity-0 mt-0'
                }`}>
                  <div className="overflow-hidden">
                    
                    {/* Inner Content of the Mini View */}
                    <div className="border-t border-gray-200 pt-6 flex flex-col md:flex-row gap-6">
                      
                      {/* Left Side: Media & Core Data (Mirrors UploadResultUi) */}
                      <div className="w-full md:w-1/3 bg-[#f4f4f5] rounded-2xl p-4 flex flex-col border border-black/5">
                        <div className="bg-zinc-800 rounded-xl w-full h-40 mb-4 flex items-center justify-center overflow-hidden">
                          <p className="text-white/50 italic text-xs text-center px-4">Detected Damage<br/>Preview</p>
                        </div>
                        <h4 className="text-lg font-black text-black mb-3 truncate" title={report.fileName}>{report.fileName}</h4>
                        <div className="space-y-2 text-sm text-black">
                          <div className="flex justify-between border-b border-black/10 pb-1">
                            <span className="font-bold">Damage Type:</span>
                            <span>{report.type}</span>
                          </div>
                          <div className="flex justify-between border-b border-black/10 pb-1">
                            <span className="font-bold">AI Confidence:</span>
                            <span className="text-blue-600 font-black">{report.confidence}</span>
                          </div>
                        </div>
                      </div>

                      {/* Right Side: AI Insights & Actions */}
                      <div className="w-full md:w-2/3 flex flex-col justify-between">
                        <div>
                          <h4 className="text-black font-black text-lg mb-2 uppercase tracking-wide">Detection Details</h4>
                          <p className="text-zinc-600 text-sm font-medium leading-relaxed mb-4">
                            {report.description}
                          </p>
                          
                          {/* AI Observations Box */}
                          <div className="bg-blue-50/50 p-4 rounded-xl border border-blue-100 mb-6">
                            <h4 className="font-black text-xs mb-2 text-blue-700 uppercase tracking-widest">AI Observations:</h4>
                            <ul className="text-sm space-y-1 list-disc list-inside text-zinc-700 font-medium">
                              {report.aiObservations.map((obs, idx) => (
                                <li key={idx}>{obs}</li>
                              ))}
                            </ul>
                          </div>
                        </div>

                        {/* Mini View Actions & Metadata */}
                        <div className="flex flex-col sm:flex-row justify-between items-center gap-4 pt-4 border-t border-zinc-200">
                          <div className="flex gap-4">
                            <div>
                              <span className="text-[10px] text-zinc-400 font-black uppercase tracking-widest block mb-0.5">Current Status</span>
                              <span className="text-xs text-black font-bold">{report.status}</span>
                            </div>
                            <div>
                              <span className="text-[10px] text-zinc-400 font-black uppercase tracking-widest block mb-0.5">Coordinates</span>
                              <span className="text-xs text-blue-500 font-bold hover:underline cursor-pointer">View Map &rarr;</span>
                            </div>
                          </div>

                          <div className="flex gap-2 w-full sm:w-auto">
                            <button className="flex-1 sm:flex-none bg-green-500 text-white px-6 py-2.5 rounded-full font-bold text-xs hover:bg-green-600 transition-colors shadow-md">
                              Mark Resolved
                            </button>
                            <button className="flex-1 sm:flex-none bg-zinc-900 text-white px-6 py-2.5 rounded-full font-bold text-xs hover:bg-black transition-colors shadow-md">
                              Update Details
                            </button>
                          </div>
                        </div>
                      </div>

                    </div>
                  </div>
                </div>

              </div>
            );
          })}
        </div>

      </div>
    </div>
  );
}